
## Server name ##
spring:
  profiles:
    active: peer1
---
## 高可用环境1 ##
spring:
  profiles: peer1

## Server Port ##
server:
  port: 8761

## eureka ##
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
---
### 高可用环境2 ##
spring:
  profiles: peer2

## Server Port ##
server:
  port: 8762

## eureka ##
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

---
spring:
  # APP信息 #
  application:
    name: cloud-eureka-server
  # 安全 #
  security:
    user:
      name: eureka
      password: Jasmine1017
## eureka ##
eureka:
  instance:
    hostname: 127.0.0.1
    status-page-url-path: ${}
  client:
    register-with-eureka: false
    fetch-registry: false
## 管理节点 ##
management:
  server:
    servlet:
      context-path: /admin